# Generated by Django 5.2.12 on 2026-03-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV SERIES')], default='movie', max_length=10),
        ),
    ]
