# Generated by Django 5.2.12 on 2026-03-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_alter_movie_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
